// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(CellarContext))]
    [Migration("20240710131256_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainModel.Bottle", b =>
                {
                    b.Property<int>("BottleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BottleId"));

                    b.Property<string>("Appellation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BottleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BottleYear")
                        .HasColumnType("int");

                    b.Property<int>("CellarId")
                        .HasColumnType("int");

                    b.Property<int>("DrawerNb")
                        .HasColumnType("int");

                    b.Property<DateTime>("IdealPeak")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeakEnd")
                        .HasColumnType("int");

                    b.Property<int>("PeakStart")
                        .HasColumnType("int");

                    b.Property<int>("StackInDrawerNb")
                        .HasColumnType("int");

                    b.Property<string>("WineColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BottleId");

                    b.HasIndex("CellarId");

                    b.ToTable("Bottle");
                });

            modelBuilder.Entity("DomainModel.Cellar", b =>
                {
                    b.Property<int>("CellarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CellarId"));

                    b.Property<int?>("CellarCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CellarModelId")
                        .HasColumnType("int");

                    b.Property<string>("CellarName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NbRow")
                        .HasColumnType("int");

                    b.Property<int>("NbStackRow")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CellarId");

                    b.HasIndex("CellarCategoryId");

                    b.HasIndex("CellarModelId");

                    b.HasIndex("UserId");

                    b.ToTable("Cellar");
                });

            modelBuilder.Entity("DomainModel.CellarCategory", b =>
                {
                    b.Property<int>("CellarCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CellarCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CellarCategoryId");

                    b.ToTable("CellarCategory");
                });

            modelBuilder.Entity("DomainModel.CellarModel", b =>
                {
                    b.Property<int>("CellarModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CellarModelId"));

                    b.Property<string>("CellarBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CellarTemperature")
                        .HasColumnType("int");

                    b.HasKey("CellarModelId");

                    b.ToTable("CellarModel");
                });

            modelBuilder.Entity("DomainModel.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DomainModel.Bottle", b =>
                {
                    b.HasOne("DomainModel.Cellar", "Cellar")
                        .WithMany("Bottles")
                        .HasForeignKey("CellarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cellar");
                });

            modelBuilder.Entity("DomainModel.Cellar", b =>
                {
                    b.HasOne("DomainModel.CellarCategory", "CellarCategory")
                        .WithMany("Cellars")
                        .HasForeignKey("CellarCategoryId");

                    b.HasOne("DomainModel.CellarModel", "CellarModel")
                        .WithMany("Cellars")
                        .HasForeignKey("CellarModelId");

                    b.HasOne("DomainModel.User", "User")
                        .WithMany("Cellars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellarCategory");

                    b.Navigation("CellarModel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainModel.Cellar", b =>
                {
                    b.Navigation("Bottles");
                });

            modelBuilder.Entity("DomainModel.CellarCategory", b =>
                {
                    b.Navigation("Cellars");
                });

            modelBuilder.Entity("DomainModel.CellarModel", b =>
                {
                    b.Navigation("Cellars");
                });

            modelBuilder.Entity("DomainModel.User", b =>
                {
                    b.Navigation("Cellars");
                });
#pragma warning restore 612, 618
        }
    }
}
